spring:
  profiles:
    active: dev
    group:
      dev: low-level-logging, console-logging
      test: low-level-logging, console-logging, file-logging
      prod: high-level-logging, console-logging, file-logging